[[redirects]]
  from = "/"
  to = "/jp"
  status = 302
  force = true
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/"
  to = "/pl"
  status = 302
  force = true
  conditions = {Language = ["pl"]}

[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 200
  force = true